# Site
name: "Shardul's Tech Blog"
title: "Shardul's Tech Blog"
description: "Multi Cloud and Big Data Technologies"
logo: 'assets/images/logo1.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-PNEQ8HXLQ6'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  shardul:
    name: Shardul
    display_name: Shardul    
    avatar: 'assets/images/shardul.jpeg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: shardul.srivastava007@gmail.com
    web: https://shardul.dev
    twitter: https://twitter.com/shardulsrvstv
    description: "Shardul is a seasoned Engineering Leader and Cloud expert focused on Data and Infrastructure"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/

highlighter: rouge

# Other
markdown: kramdown
# markdown: GFM

# These are not working
# redcarpet:
#     extensions: ["fenced_code_blocks","no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

kramdown:
  input: GFM
  # syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    block:
      line_numbers: false

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-4339608862775894"
adsense-data-ad-slot: "4791457368"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

theme: jekyll